api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "delivery-customization"

uid = "7caef09d-bc92-c4fe-9c8c-5e43dc1b38bce5a7fa55"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.delivery-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
